name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: checkboxes
    id: existing_issue
    attributes:
      label: "Is there an existing issue for this?"
      options:
        - label: "I have searched the existing issues"
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Explain the problem

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe your idea
